### ISSUE TITLE
没有编译后的发行版本吗？

### ISSUE THREAD

**Issue by Jun47** [lysilver/KopSoftWms#20]
只有源码，小白不会安装啊，大哭。。。

**Comment by lysilver** [comment]
数据库这些还是需要手动的（编译之后），需要的话，可以编译发布到releases

**Comment by Kissycat** [comment]
> 数据库这些还是需要手动的（编译之后），需要的话，可以编译发布到releases

老板，这数据库需要怎么连呀，我用的mysql，已经建好空白的库和用户名了，但是在这个设置文件里修改，重启后还是提示连不上..
![image](https://user-images.githubusercontent.com/20614068/210495698-513fb3e2-02e3-4dfd-9057-0689960acdb9.png)

**Comment by lysilver** [comment]
![image](https://user-images.githubusercontent.com/44791098/210724948-f5655264-33c8-4f69-b321-763d8672982c.png)
修改这个
