### ISSUE TITLE
仓库类型

### ISSUE THREAD

**Issue by wangaili** [lysilver/KopSoftWms#23]
在入库管理时，使用仓库类型字段会有bug。

**Comment by lysilver** [comment]
> 在入库管理时，使用仓库类型字段会有bug。

好的，我看下

**Comment by lysilver** [comment]
![image](https://user-images.githubusercontent.com/44791098/219829970-806d113f-80cd-4b6b-b092-ea71b40b4a72.png)
没有bug？？？

**Comment by wangaili** [comment]
请问怎么解决linux系统中数据库表名大小写不匹配的问题呀

**Comment by lysilver** [comment]
> 请问怎么解决linux系统中数据库表名大小写不匹配的问题呀

![image](https://user-images.githubusercontent.com/44791098/222959353-9ee38be9-23b6-4fbb-80a7-ef47f6cd4d98.png)
![image](https://user-images.githubusercontent.com/44791098/222959413-573e45b3-3021-4b60-80a1-359855b439ea.png)

**上面两种方法**

**Comment by wangaili** [comment]
感谢解答，但是最近发现新的问题，当物料数目大于100个时，之后的物料无法在入库明细中进行选择添加了。

**Comment by lysilver** [comment]
![image](https://user-images.githubusercontent.com/44791098/225011090-a5b9cc79-5723-4db5-811d-5eb5bbcd9cae.png)

当时的逻辑是默认显示100条数据，剩下的需要前台下拉框那可以搜索  或者后端修改

**Comment by wangaili** [comment]
下拉框搜索不到100条之后的物料
