### ISSUE TITLE
连不上数据库

### ISSUE THREAD

**Issue by Max-Wang-M** [lysilver/KopSoftWms#26]
![1694076438591](https://github.com/lysilver/KopSoftWms/assets/75629329/86f60c88-e96e-4064-87ee-54581049c531)
![image](https://github.com/lysilver/KopSoftWms/assets/75629329/27be06e3-8d63-4c8d-9037-f7cdb7865572)

**Comment by lysilver** [comment]
![image](https://github.com/lysilver/KopSoftWms/assets/44791098/2eaf12ce-7d04-4f8b-865e-bac7ca257161)
断点看下这个获取的是啥？

**Comment by Max-Wang-M** [comment]
![image](https://github.com/lysilver/KopSoftWms/assets/75629329/03df8e56-5cea-44a1-b2c7-4b56c8ea5270)

**Comment by Max-Wang-M** [comment]
![image](https://github.com/lysilver/KopSoftWms/assets/75629329/ebdd2a7c-3f81-4f35-954b-cbfe06d51355)

**Comment by lysilver** [comment]
把mysql系统表的user表中root用户对应的Host改成% ，不行加我qq（代码提交记录有qq）
