### ISSUE TITLE
不能登录，报错

### ISSUE THREAD

**Issue by joket1999** [lysilver/KopSoftWms#6]
登录返回的数据，貌似是数据库连接不了。
系统：Alpine 3.9
数据库：mysql 5.7

```javascript
{"Item1":false,"Item2":"异常"}
```
![image](https://user-images.githubusercontent.com/6611880/58783884-a52a6e00-8614-11e9-86a1-4c7b892d339e.png)

------------------------------------
用项目里的Dockerfile打包镜像，运行容器也不行，也是登录不了

**Comment by lysilver** [comment]
log日志
